# Generated by Django 4.0.3 on 2022-03-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='DateOfBirth',
            field=models.DateField(default='1999-08-15'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='DateOfBirth',
            field=models.DateField(default='1999-08-15'),
        ),
    ]
