# Generated by Django 4.0.3 on 2022-03-08 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0002_alter_doctor_dateofbirth_alter_patient_dateofbirth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_Schedule_Date', models.DateField()),
                ('Doctor_Schedule_Start_Time', models.TimeField()),
                ('Doctor_Schedule_End_Time', models.TimeField()),
                ('Average_Consulting_Time', models.CharField(max_length=50)),
                ('Doctor_Schedule_Status', models.BooleanField(default=False)),
                ('Doctor_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.doctor')),
            ],
        ),
    ]
