# Generated by Django 4.0.3 on 2022-03-08 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0003_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Appointment_Number', models.CharField(max_length=50)),
                ('Reason', models.CharField(max_length=100)),
                ('Appointment_Time', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Patient_Come', models.CharField(max_length=100)),
                ('Doctor_Comment', models.CharField(max_length=100)),
                ('Patient_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.patient')),
                ('Schedule_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.schedule')),
            ],
        ),
    ]
