# Generated by Django 4.0.3 on 2022-03-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0004_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Appointment_Time',
            new_name='Appointment_Date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Appointment_End_Time',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='Appointment_Start_Time',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
